import Link from 'next/link';
import { redirect } from 'next/navigation';
import {
  can,
  round2,
  type PayslipDto,
  type PayrunDto,
  type EmployeeDetailDto,
} from '@peoplepay360/shared';
import { getSession } from '@/lib/session';
import { apiGetOrRedirect, apiFetch } from '@/lib/api-client';
import { formatDate, formatMoney, splitName } from '@/lib/utils';
import { PageHeader, StatusBadge, Avatar, EmptyState, KpiCard } from '@/components/ui';
import { ListFilters } from '@/components/list-filters';

export const dynamic = 'force-dynamic';

export default async function PayslipsPage({
  searchParams,
}: {
  searchParams: Promise<{ employee?: string; status?: string; payrun?: string; q?: string }>;
}) {
  const session = await getSession();
  if (!session) redirect('/login');

  const params = await searchParams;

  const [payslips, payruns, employee] = await Promise.all([
    apiGetOrRedirect<PayslipDto[]>('/payslips', '/my-space', {
      employeeId: params.employee,
      status: params.status,
      payrunId: params.payrun,
      q: params.q,
    }),
    apiGetOrRedirect<PayrunDto[]>('/payruns', '/my-space'),
    params.employee
      ? apiFetch<EmployeeDetailDto | null>(`/employees/${params.employee}`, { nullOn404: true })
      : Promise.resolve(null),
  ]);

  const totalNet = round2(payslips.reduce((s, p) => s + p.netPay, 0));
  const totalGross = round2(payslips.reduce((s, p) => s + p.grossPay, 0));

  return (
    <>
      <PageHeader
        title="Payslips"
        subtitle={
          employee
            ? `Payslips for ${employee.fullName}`
            : `${payslips.length} payslip${payslips.length === 1 ? '' : 's'}`
        }
        breadcrumb={
          employee
            ? [
                { label: 'Employees', href: '/employees' },
                { label: employee.fullName, href: `/employees/${employee.id}` },
                { label: 'Payslips', href: `/payroll/payslips?employee=${employee.id}` },
              ]
            : undefined
        }
      />

      <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <KpiCard label="Payslips" value={payslips.length} />
        <KpiCard label="Total Gross" value={formatMoney(totalGross)} />
        <KpiCard label="Total Net" value={formatMoney(totalNet)} tone="positive" />
        <KpiCard
          label="Average Net"
          value={formatMoney(payslips.length > 0 ? round2(totalNet / payslips.length) : 0)}
        />
      </div>

      <ListFilters
        search={{ value: params.q ?? '', placeholder: 'Search number or employee…' }}
        selects={[
          {
            name: 'status',
            label: 'Status',
            value: params.status ?? '',
            options: [
              { value: '', label: 'All statuses' },
              { value: 'DRAFT', label: 'Draft' },
              { value: 'COMPUTED', label: 'Computed' },
              { value: 'VALIDATED', label: 'Validated' },
              { value: 'PAID', label: 'Paid' },
            ],
          },
          {
            name: 'payrun',
            label: 'Pay Run',
            value: params.payrun ?? '',
            options: [
              { value: '', label: 'All pay runs' },
              ...payruns.map((p) => ({ value: p.id, label: p.name })),
            ],
          },
        ]}
      />

      {payslips.length === 0 ? (
        <div className="mt-4">
          <EmptyState
            title="No payslips"
            description="Payslips are generated by computing a pay run."
            action={
              can(session.role, 'payruns', 'create') ? (
                <Link href="/payroll/payruns/new" className="btn-primary">
                  New Pay Run
                </Link>
              ) : null
            }
          />
        </div>
      ) : (
        <div className="table-wrap mt-4">
          <table className="table">
            <thead>
              <tr>
                <th>Employee</th>
                <th>Number</th>
                <th>Period</th>
                <th>Pay Run</th>
                <th>Worked Days</th>
                <th>Gross</th>
                <th>Net</th>
                <th>Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {payslips.map((p) => {
                const { first, last } = splitName(p.employee?.fullName ?? '');
                return (
                  <tr key={p.id}>
                    <td>
                      <Link
                        href={`/employees/${p.employeeId}`}
                        className="flex items-center gap-2.5 hover:text-brand-700"
                      >
                        <Avatar firstName={first} lastName={last} size="sm" seed={p.employeeId} />
                        <span>
                          <span className="block font-medium text-slate-900">
                            {p.employee?.fullName}
                          </span>
                          <span className="block text-xs text-slate-500">
                            {p.employee?.department ?? '—'}
                          </span>
                        </span>
                      </Link>
                    </td>
                    <td className="font-mono text-xs">{p.number}</td>
                    <td className="text-xs">{formatDate(p.periodStart)}</td>
                    <td className="text-xs">
                      {p.payrun ? (
                        <Link
                          href={`/payroll/payruns/${p.payrunId}`}
                          className="text-brand-600 hover:underline"
                        >
                          {p.payrun.name}
                        </Link>
                      ) : (
                        '—'
                      )}
                    </td>
                    <td>{p.workedDays}</td>
                    <td>{formatMoney(p.grossPay)}</td>
                    <td className="font-semibold text-slate-900">{formatMoney(p.netPay)}</td>
                    <td>
                      <StatusBadge status={p.status} />
                    </td>
                    <td>
                      <Link
                        href={`/payroll/payslips/${p.id}`}
                        className="text-xs font-medium text-brand-600 hover:underline"
                      >
                        Open
                      </Link>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}
