import Link from 'next/link';
import { redirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { getSession } from '@/lib/auth';
import { can } from '@/lib/rbac';
import { formatDate, formatMoney, round2 } from '@/lib/utils';
import { PageHeader, StatusBadge, Avatar, EmptyState, KpiCard } from '@/components/ui';
import { ListFilters } from '@/components/list-filters';

export const dynamic = 'force-dynamic';

export default async function PayslipsPage({
  searchParams,
}: {
  searchParams: Promise<{ employee?: string; status?: string; payrun?: string; q?: string }>;
}) {
  const session = await getSession();
  if (!session) redirect('/login');
  if (!can(session.role, 'payslips', 'read')) redirect('/dashboard');

  const params = await searchParams;

  const where = {
    ...(params.employee ? { employeeId: params.employee } : {}),
    ...(params.status ? { status: params.status } : {}),
    ...(params.payrun ? { payrunId: params.payrun } : {}),
    ...(params.q
      ? {
          OR: [
            { number: { contains: params.q } },
            { employee: { firstName: { contains: params.q } } },
            { employee: { lastName: { contains: params.q } } },
          ],
        }
      : {}),
  };

  const [payslips, payruns, employee] = await Promise.all([
    prisma.payslip.findMany({
      where,
      include: {
        employee: { include: { department: true } },
        payrun: true,
        structure: true,
      },
      orderBy: [{ periodStart: 'desc' }, { number: 'desc' }],
      take: 300,
    }),
    prisma.payrun.findMany({ orderBy: { periodStart: 'desc' }, take: 24 }),
    params.employee
      ? prisma.employee.findUnique({ where: { id: params.employee } })
      : Promise.resolve(null),
  ]);

  const totalNet = round2(payslips.reduce((s, p) => s + p.netPay, 0));
  const totalGross = round2(payslips.reduce((s, p) => s + p.grossPay, 0));

  return (
    <>
      <PageHeader
        title="Payslips"
        subtitle={
          employee
            ? `Payslips for ${employee.firstName} ${employee.lastName}`
            : `${payslips.length} payslip${payslips.length === 1 ? '' : 's'}`
        }
        breadcrumb={
          employee
            ? [
                { label: 'Employees', href: '/employees' },
                { label: `${employee.firstName} ${employee.lastName}`, href: `/employees/${employee.id}` },
                { label: 'Payslips', href: `/payroll/payslips?employee=${employee.id}` },
              ]
            : undefined
        }
      />

      <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <KpiCard label="Payslips" value={payslips.length} />
        <KpiCard label="Total Gross" value={formatMoney(totalGross)} />
        <KpiCard label="Total Net" value={formatMoney(totalNet)} tone="positive" />
        <KpiCard
          label="Average Net"
          value={formatMoney(payslips.length > 0 ? round2(totalNet / payslips.length) : 0)}
        />
      </div>

      <ListFilters
        search={{ value: params.q ?? '', placeholder: 'Search number or employee…' }}
        selects={[
          {
            name: 'status',
            label: 'Status',
            value: params.status ?? '',
            options: [
              { value: '', label: 'All statuses' },
              { value: 'DRAFT', label: 'Draft' },
              { value: 'COMPUTED', label: 'Computed' },
              { value: 'VALIDATED', label: 'Validated' },
              { value: 'PAID', label: 'Paid' },
            ],
          },
          {
            name: 'payrun',
            label: 'Pay Run',
            value: params.payrun ?? '',
            options: [
              { value: '', label: 'All pay runs' },
              ...payruns.map((p) => ({ value: p.id, label: p.name })),
            ],
          },
        ]}
      />

      {payslips.length === 0 ? (
        <div className="mt-4">
          <EmptyState
            title="No payslips"
            description="Payslips are generated by computing a pay run."
            action={
              can(session.role, 'payruns', 'create') ? (
                <Link href="/payroll/payruns/new" className="btn-primary">
                  New Pay Run
                </Link>
              ) : null
            }
          />
        </div>
      ) : (
        <div className="table-wrap mt-4">
          <table className="table">
            <thead>
              <tr>
                <th>Employee</th>
                <th>Number</th>
                <th>Period</th>
                <th>Pay Run</th>
                <th>Worked Days</th>
                <th>Gross</th>
                <th>Net</th>
                <th>Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {payslips.map((p) => (
                <tr key={p.id}>
                  <td>
                    <Link
                      href={`/employees/${p.employeeId}`}
                      className="flex items-center gap-2.5 hover:text-brand-700"
                    >
                      <Avatar
                        firstName={p.employee.firstName}
                        lastName={p.employee.lastName}
                        size="sm"
                        seed={p.employeeId}
                      />
                      <span>
                        <span className="block font-medium text-slate-900">
                          {p.employee.firstName} {p.employee.lastName}
                        </span>
                        <span className="block text-xs text-slate-500">
                          {p.employee.department?.name ?? '—'}
                        </span>
                      </span>
                    </Link>
                  </td>
                  <td className="font-mono text-xs">{p.number}</td>
                  <td className="text-xs">{formatDate(p.periodStart)}</td>
                  <td className="text-xs">
                    {p.payrun ? (
                      <Link
                        href={`/payroll/payruns/${p.payrunId}`}
                        className="text-brand-600 hover:underline"
                      >
                        {p.payrun.name}
                      </Link>
                    ) : (
                      '—'
                    )}
                  </td>
                  <td>{p.workedDays}</td>
                  <td>{formatMoney(p.grossPay)}</td>
                  <td className="font-semibold text-slate-900">{formatMoney(p.netPay)}</td>
                  <td>
                    <StatusBadge status={p.status} />
                  </td>
                  <td>
                    <Link
                      href={`/payroll/payslips/${p.id}`}
                      className="text-xs font-medium text-brand-600 hover:underline"
                    >
                      Open
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}
